### ISSUE TITLE
Tags filtering not working

### ISSUE THREAD

**Issue by mihaivint** [simplesurance/grpcconsulresolver#19]
Seems that tags are not passed for filtering. 

Example service definition 
curl -X PUT -d '{"ID": "grpc-node0", "Name": "spicedb", "Address": "10.150.14.37", "Port": 50051, "Tags": ["grpc","test"]}' http://127.0.0.1:8500/v1/agent/service/register

And when called with:
        client, err := grpc.Dial(
                "consul://10.150.14.248:8500/spicedb?scheme=https&tags=grpc",
                grpc.WithDefaultServiceConfig(`{"loadBalancingPolicy": "round_robin"}`),
                grpc.WithInsecure(),
        )

It'll return all services no matter the tags, as they are not passed at all.

**Comment by fho** [comment]
This is broken since grpc-go 1.42 already.
Before target.Endpoint contained also the query string.
This changed in https://github.com/grpc/grpc-go/pull/4817/files#diff-ce683c132234ad155738e60c1fabf51c62d442813d0d650662de4ff991cebfa3L251.

**Comment by fho** [comment]
fixed via https://github.com/simplesurance/grpcconsulresolver/pull/20
