### ISSUE TITLE
If i cant connect to my server-side server, i want to know the result which the consul returned, like host and post. How coulud i find the variable in the debug model?

### ISSUE THREAD

**Issue by INGg** [simplesurance/grpcconsulresolver#39]
My question is on my title. Because I have this problem: "last resolver error: produced zero addresses". So i want to know the result which consul returned.  i cant find the variable position. If someone can tell my solution, thank u very much XD!

**Comment by fho** [comment]
Hello,

the  package uses the grpc logger  to log traditional information, you can try to set the grpc logger, if you haven't already: (`grpclog.SetLoggerV2(...)`.


From the message I would  guess that either you service name in consul differs, your service healthcheck is negative in consul or you have configured grpcconsulresolver to only use healthy services,
